##### **Step 1 : Import Packages**

In [1]:
import numpy as pd
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [2]:
path1='Visadataset.csv'
pd.read_csv(path1)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**step 2: Read the data**

In [10]:
path='bank.csv'
bank_df=pd.read_csv(path)
bank_df

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

**Step-3: Data quick checks visadf**

-columns

-shape

-dtype

-len

-head

-info

-isnullm

In [ ]:
path1='Visadataset.csv'
visa_df=pd.read_csv(path1)
visa_df

In [ ]:
visa_df.columns

In [ ]:
visa_df.shape
print('The number of columns are:'visa_df.shape[1])
print('The number of rows are:'visa_df.shape[0])

In [ ]:
visa_df.dtypes

In [ ]:
types=visa_df.dtypes
type_df=pd.DataFrame(types).reset_index()
type_df.columns=['Columns_Name','Data Type']
type_df

In [ ]:
types.keys()

In [ ]:
types.values
# not call able means remove the brackets 
# type

In [ ]:
dir(types))

In [ ]:
# step :1
types=visa_df.dtypes
# step :2
keys=types.keys().tolist()
# step :3
values=types.values.tolist()
keys
values

In [ ]:
zip(keys,strict=False)

In [ ]:
type_df=pd.DataFrame(zip(keys,values),
                     columns=['Columns','Type'])
type_df

In [ ]:
type_df.to_csv('Datatype.csv',index=False)

In [ ]:
cat=[]
num=[]
for i,j in zip(keys,values):
    #print(i,j)
    if j=='object':
        cat.append(i)
    else:
        num.append(i)

In [ ]:
cat

In [ ]:
num

**Selct_dtype**

In [ ]:
visa_df.select_dtypes(include='object').columns

In [ ]:
visa_df.select_dtypes(exclude='object').columns

**Task :2**

In [ ]:
visa_df

In [ ]:
visa_df['continent']
# one bracket is one dimensional

In [ ]:
visa_df['continent']=='Asia'

In [ ]:
# step :1- main Dataframe
visa_df['continent']
# step :2- select continent column
visa_df['continent']
# step :3- apply condition
visa_df['continent']=='Asia'
# step :4- extract the true values
con=visa_df['continent']=='Asia'
len(visa_df[con])

**Unique**

In [ ]:
visa_df['continent'].unique()

**Nunique**

In [ ]:
visa_df['continent'].nunique()

In [ ]:
labels=visa_df['continent'].unique()
for i in labels:
    con=visa_df['continent']==i
    count=(len(visa_df[con]))
    print(count)

In [ ]:
con=visa_df['continent']==i
len(visa_df[con])

In [ ]:
labels=visa_df['continent'].unique()
for i in labels:
    con=visa_df['continent']==i
    count=(len(visa_df[con]))
    print(count)

In [ ]:
import numpy as pd
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [ ]:
path='Visadataset.csv'
pd.read_csv(path)

In [ ]:
cat=visa_df.select_dtypes(include='object').columns

In [ ]:
num=visa_df.select_dtypes(exclude='object').columns

## Raw Data

In [ ]:
visa_df  # DataFrame
visa_df['continent']  # series
visa_df['continent'].values # arrray of values

**Frequency Table**

In [ ]:
con=visa_df['continent']=='Asia'
len(visa_df[con])

In [ ]:
visa_df['continent'].unique()

In [ ]:
labels=visa_df['continent'].unique()
count=[]
for i in labels:
    con=visa_df['continent']==i
    count.append(len(visa_df[con]))
count

In [ ]:
# we have two list
# one list name : labels

pd.DataFrame(zip(labels,count),columns=['continent','No. of Applicant'])

In [ ]:
# All together
path='Visadataset.csv'  # data frame
pd.read_csv(path)

cat=visa_df.select_dtypes(include='object').columns   # Select the dtypes
num=visa_df.select_dtypes(exclude='object').columns

labels=visa_df['continent'].unique()        # considering the vales into 'i'
count=[]
for i in labels:
    con=visa_df['continent']==i
    count.append(len(visa_df[con]))
count

continent_df=pd.DataFrame(zip(labels,count),      # we have two list converting into dataframe
                          columns=['Continent','No. of Applicant'])

continent_df.to_csv('continent_df.csv',index=False)   # print the values into another csv file

In [ ]:
continent_df

## Value_counts

In [ ]:
visa_df['continent'].value_counts()

In [ ]:
# dividing the continent into a group
# then calculate size of each group
visa_df.groupby('continent').size()

In [ ]:
visa_df['continent'].values

In [ ]:
visa_df['continent'].keys()

In [ ]:
pd.DataFrame(zip(keys,values),columns=['Cotinent_keys','Continent_values'])

In [ ]:
# Sir method 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
continent_df=pd.DataFrame(zip(continent_key,continent_values),
                         columns=['continent','no of continent'])
continent_df

## Bar Chart

- under matplotlib

- plt.bar

-

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.bar(continent_key,continent_values)

In [ ]:
plt.bar()

In [ ]:
# fig size 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.figure(figsize=(10,4))
plt.bar(continent_key,continent_values)

In [ ]:
# colurs 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
col=['blue','red','yellow','green','orange','black']
plt.figure(figsize=(10,4))
plt.bar(continent_key,
        continent_values,
        color=col)

In [ ]:
# we can provide the names also 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
col=['blue','red','yellow','green','orange','black']
plt.figure(figsize=(10,4))
plt.bar(continent_key,continent_values,color=col)
plt.xlabel('Continent')
plt.ylabel('No of Continent')
plt.title('Continent_bar')

In [ ]:
# to aviod the right up 
# we can save the figure
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
col=['blue','red','yellow','green','orange','black']
plt.figure(figsize=(10,4))
plt.bar(continent_key,continent_values,color=col)
plt.xlabel('Continent')
plt.ylabel('No of Continent')
plt.title('Continent_bar')
plt.savefig('Continent_Bar.png')
plt.savefig('Continent_Bar.jpg')
plt.show()

## Pie Chart

**Relative frequency**

In [ ]:
visa_df['continent'].value_counts(normalize=True)*100

In [ ]:
plt.pie()

In [ ]:
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.pie(continent_values,
       labels=continent_key)
plt.show() # show is used to remove the write ups

In [ ]:
# to see the percentage we need to use autopct
# 0.2= 2 decimals f = format 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.pie(continent_values,
       labels=continent_key,
       autopct="%0.2f%%")
plt.show()

In [ ]:
# applying the start angel means rotate 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.pie(continent_values,
       labels=continent_key,
       autopct="%0.2f%%",
       startangle=45)
plt.show()

In [ ]:
# using the explode means break the pie chart into 6 parts 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.pie(continent_values,
        explode=[0.1,0.1,0.1,0.1,0.1,0.1],
       labels=continent_key,
       autopct="%0.2f%%",
       startangle=45)
plt.show()

In [ ]:
# to increase the size of the pie chart we use radius 
continent_key=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.pie(continent_values,
        explode=[0.1,0.1,0.1,0.1,0.1,0.1],
       labels=continent_key,
       autopct="%0.2f%%",
       startangle=45,
       radius=3)
plt.show()